-- ~\AppData\Local\nvim\lua\myconfig\standalone\keymaps.lua
-- =============================================================================
-- STANDALONE-ONLY KEYMAPS
-- =============================================================================
-- Additional keymaps that only apply to standalone Neovim
-- Core shared keymaps are in myconfig/core/keymaps.lua
-- =============================================================================
-- These are already set in core/keymaps.lua when not in VSCode
-- This file is for any additional standalone-specific keymaps
-- Plugin-specific keymaps are defined in their respective plugin files:
-- - Telescope keymaps → plugins/telescope.lua
-- - LSP keymaps → plugins/lsp.lua
-- - Oil keymaps → plugins/oil.lua
-- - etc.
-- You can add any extra standalone keymaps here as needed
